### ISSUE TITLE
Error: Download drivers error, please reinstall read ECONNRESET

### ISSUE THREAD

**Issue by doomsbuster** [imsobear/node-browser#1]
Cannot install node-browser on macOS Sierra. Getting error below.

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> node-browser@0.0.3 install /path/node_modules/node-browser
> node ./build.js

load: download webDrivers...
/path/node_modules/node-browser/build.js:64
          throw new Error('Download drivers error, please reinstall ' + err.message);
          ^

Error: Download drivers error, please reinstall read ECONNRESET
    at /path/node_modules/node-browser/build.js:64:17
    at /path/node_modules/download/index.js:154:4
    at Request.callback (/path/node_modules/each-async/index.js:33:4)
    at Request.onetime (/path/node_modules/onetime/index.js:22:12)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/path/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-browser"
npm ERR! node v6.0.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! node-browser@0.0.3 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-browser@0.0.3 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-browser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-browser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-browser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/npm-debug.log
```

**Comment by jpike88** [comment]
+1
