### ISSUE TITLE
Could not install node-browser

### ISSUE THREAD

**Issue by lekshcs** [imsobear/node-browser#3]
Tried to install node-browser via npm . Having specifications like
OS: Windows 10
Node version : 8.10.0

It throws errors like below

> node-browser@0.0.3 install \var\node_modules\node-browser
> node ./build.js

load: download webDrivers...
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '\var\node_modules\node-browser\driver\chromedriver.exe-dir\chromedriver'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (\var\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (\var\node_modules\fs-extra\lib\copy-sync\copy-sync.js:20:58)
    at reworkDest (\var\node_modules\node-browser\build.js:113:7)
    at \var\node_modules\node-browser\build.js:85:13
    at ConcatStream.<anonymous> (\var\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (\var\node_modules\readable-stream\lib\_stream_writable.js:620:14)
    at endWritable (\var\node_modules\readable-stream\lib\_stream_writable.js:628:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-browser@0.0.3 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-browser@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by delphin-germa-orange** [comment]
+1 please
